---
# Tasks file for roles/ubuntu-install
- name: Install Java
  apt:
    name: default-jre
    state: present
    update_cache: yes

- name: Install ansible, boto, and openstack via pip
  pip:
    name:
      - ansible
      - boto
      - python-openstackclient
