---
# tasks file for roles/ubuntu-monitor/grafana

- name: Adding key to the package
  become: yes
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add to the grafana repository
  shell: echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

- name: Updating ubuntu
  become: yes
  yum:
    update_cache: yes

- name: Installing grafana
  become: yes
  dnf:
    name: grafana
    state: present
