---
# tasks file for roles/install_at_centos

- name: dhcp installment at centos
  yum:
    name: dhcp-server
    state: latest
    update-cache: yes

- name: bind9 installment at centos
  yum:
    name:
      - bind
      - bind-utils
    state: latest
    update_cache: yes

- name: samba installment at centos
  yum:
    name:
      - samba
      - samba-client
      - samba-common
    state: latest
    update_cache: yes

- name: httpd installment at centos
  yum:
    name: httpd
    state: latest
    update_cache: yes

- name: mariadb installment at centos
  yum:
    name: mariadb
    state: latest
    update_cache: yes

